# Generated by Django 6.0.2 on 2026-03-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('contact', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
            ],
        ),
    ]
